### ISSUE TITLE
Status command crashes if database is empty

### ISSUE THREAD

**Issue by SzoDavid** [SzoDavid/WordChain#38]
If the database is empty running /status throws an error:

```
Uncaught CombinedPropertyError Error: Received one or more errors
    at handle (/path/WordChain/node_modules/@sapphire/shapeshift/dist/index.js:463:70)
    at parse (/path/WordChain/node_modules/@sapphire/shapeshift/dist/index.js:142:88)
    at addFields (/path/WordChain/node_modules/@discordjs/builders/dist/messages/embed/Embed.cjs:17:42)
    at execute (/path/WordChain/commands/status.js:34:25)
```

**Comment by SzoDavid** [comment]
Maybe the issue is with parsing the channels used by the bot in the current server. Check what happens if there are channels registered in one server, but there are none in an other one. 

If this is the issue, in this case display an embed saying for example "There are <num> channels using this bot already, make it <++num> by running /set_channel"

**Comment by kovagoadi** [comment]
> Maybe the issue is with parsing the channels used by the bot in the current server. Check what happens if there are channels registered in one server, but there are none in an other one.
From what I've seen it isn't related to that. It happens because the value of statusEmbed for the current channels is set to an empty string (it is set in game/status.js, [here](https://github.com/SzoDavid/WordChain/blob/main/game/status.js#L16), then the foreach doesn't happen, because the query doen't return anything, thus the function returns an empty string for channels), which I think causes this error to occur.
